# Scratch code for testing purposes and small experiments. 


In [42]:


import numpy as np

def common_neighbors(adj):
    return np.dot(adj, adj)

def eigenvalues(adj):
    return np.linalg.eigvals(adj)

def eigenvectors(adj):
    return np.linalg.eig(adj)

    


m1 = np.array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 0],
                    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
                    [1, 1, 0, 0, 0, 1, 0, 1, 0, 0],
                    [0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
                    [1, 0, 0, 1, 0, 0, 0, 0, 1, 1],
                    [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
                    [1, 0, 0, 1, 0, 0, 1, 0, 1, 0],
                    [0, 0, 0, 0, 0, 1, 1, 1, 0, 1],
                    [0, 0, 1, 0, 1, 1, 0, 0, 1, 0]])


m2 = np.array([[0, 1, 0, 1, 0, 0, 1, 1, 0, 0],
                    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 1, 1, 0, 0, 0, 1],
                    [1, 1, 0, 0, 0, 1, 0, 1, 0, 0],
                    [0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
                    [0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
                    [1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
                    [1, 0, 0, 1, 0, 1, 0, 0, 1, 0],
                    [0, 0, 0, 0, 0, 1, 1, 1, 0, 1],
                    [0, 0, 1, 0, 1, 0, 1, 0, 1, 0]])





Eigen values of G = G1 U G2 equal to the union of eigen values of G1 and G2 ?

In [43]:
eig_g1 = eigenvalues(m1)
eig_g2 = eigenvalues(m2)

m = np.logical_or(m1, m2).astype(int)

print("Eigen values of G1", eig_g1)
print("Eigen values of G2", eig_g2)
print("Eigen values of G", np.linalg.eigvals(m))



Eigen values of G1 [ 4.         -2.56155281 -2.23606798  2.23606798  1.56155281 -1.
 -1.          1.         -1.         -1.        ]
Eigen values of G2 [ 4.         -2.56155281 -2.23606798 -1.          2.23606798  1.
  1.56155281 -1.         -1.         -1.        ]
Eigen values of G [ 4.90768271  2.17008649  1.56914969 -2.83573973  0.31110782 -1.4811943
 -0.64109268 -2.         -1.         -1.        ]


Common neighbors graph

In [44]:
print("A = ", A)

A =  [[5 1 3 3 2 2 1 3 3 2]
 [1 4 1 1 1 3 3 2 0 2]
 [3 1 5 2 3 1 2 2 3 3]
 [3 1 2 4 1 2 2 2 2 1]
 [2 1 3 1 4 2 2 1 2 2]
 [2 3 1 2 2 6 5 3 2 2]
 [1 3 2 2 2 5 6 2 2 3]
 [3 2 2 2 1 3 2 5 2 3]
 [3 0 3 2 2 2 2 2 4 2]
 [2 2 3 1 2 2 3 3 2 5]]
