In [17]:


import numpy as np
import pandas as pd

def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)


m1 = np.array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 0],
                    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
                    [1, 1, 0, 0, 0, 1, 0, 1, 0, 0],
                    [0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
                    [1, 0, 0, 1, 0, 0, 0, 0, 1, 1],
                    [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
                    [1, 0, 0, 1, 0, 0, 1, 0, 1, 0],
                    [0, 0, 0, 0, 0, 1, 1, 1, 0, 1],
                    [0, 0, 1, 0, 1, 1, 0, 0, 1, 0]])


m2 = np.array([[0, 1, 0, 1, 0, 0, 1, 1, 0, 0],
                    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 1, 1, 0, 0, 0, 1],
                    [1, 1, 0, 0, 0, 1, 0, 1, 0, 0],
                    [0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
                    [0, 0, 1, 1, 0, 0, 0, 1, 1, 0],
                    [1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
                    [1, 0, 0, 1, 0, 1, 0, 0, 1, 0],
                    [0, 0, 0, 0, 0, 1, 1, 1, 0, 1],
                    [0, 0, 1, 0, 1, 0, 1, 0, 1, 0]])


edges = pd.DataFrame(columns=['source', 'target', 'weight'])
for i in range(10):
    for j in range(10):
        if m1[i][j] == 1:
            edges = pd.concat([edges, pd.DataFrame({'source': [i+1], 'target': [j+1], 'weight': [1]})])

edges.to_csv('cospectral_graph1.txt', index=False, header=False, sep='\t') 

edges = pd.DataFrame(columns=['source', 'target', 'weight'])
for i in range(10):
    for j in range(10):
        if m2[i][j] == 1:
            edges = pd.concat([edges, pd.DataFrame({'source': [i+1], 'target': [j+1], 'weight': [1]})])

edges.to_csv('cospectral_graph2.txt', index=False, header=False, sep='\t')



polblogs_edges = pd.read_csv('../datasets/polblogs.txt', header=None, sep='\t')
polblogs = np.zeros((1222, 1222))
for row in polblogs_edges.iterrows():
    polblogs[row[1][0], row[1][1]] = 1
    polblogs[row[1][1], row[1][0]] = 1







[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
m1_star = pd.read_csv('code/DA_output/cospectral_graph1.txt', sep='\t', header=None).to_numpy()
m2_star = pd.read_csv('code/DA_output/cospectral_graph2.txt', sep='\t', header=None).to_numpy()
polblogs_star = pd.read_csv('code/DA_output/polblogs.txt', sep='\t', header=None).to_numpy()

m1_minus_m1_star = np.linalg.norm(m1 - m1_star, ord="fro")
m2_minus_m2_star = np.linalg.norm(m1 - m2_star, ord="fro")
polblogs_minus_polblogs_star = np.linalg.norm(polblogs - polblogs_star, ord="fro")

m1_minus_m2_star = np.linalg.norm(graph1 - rec_graph2_np, ord="fro")
m2_minus_m1_star = np.linalg.norm(graph2 - rec_graph1_np, ord="fro")

m1_square = np.dot(m1, m1.T)
m1_star_square = np.dot(m1_star, m1_star.T)

m2_square = np.dot(m2, m2.T)
m2_star_square = np.dot(m2_star, m2_star.T)




print("|| M1* - M1 || = ", m1_minus_m1_star**2)
print("|| M2* - M2 || = ", m2_minus_m2_star**2)
print("|| M1* - M2 || = ", m1_minus_m2_star**2)
print("|| M2* - M1 || = ", m2_minus_m1_star**2)
print("|| Polblogs* - Polblogs || = ", polblogs_minus_polblogs_star**2)
print("|| M1*^2 - M1^2 || = ", np.linalg.norm(m1_star_square - m1_square, ord="fro")**2)
print("|| M2*^2 - M2^2 || = ", np.linalg.norm(m2_star_square - m2_square, ord="fro")**2)

# print(np.linalg.eigvals(graph1))
# print(np.linalg.eigvals(graph2))



|| M1* - M1 || =  56.0
|| M2* - M2 || =  64.0
|| M1* - M2 || =  64.0
|| M2* - M1 || =  64.0
|| Polblogs* - Polblogs || =  4.0
|| M1*^2 - M1^2 || =  56.0
|| M2*^2 - M2^2 || =  23.999999999999996


In [ ]:

def random_graph(n, p):
    adj_matrix = np.random.choice([0, 1], size=(n, n), p=[1-p, p])
    np.fill_diagonal(adj_matrix, 0)
    adj_matrix = np.triu(adj_matrix, k=1)
    adj_matrix = adj_matrix + adj_matrix.T
    return adj_matrix

sizes = np.linspace(100, 1000, num=10, dtype=int, endpoint=True)

for size in sizes:
    random_G = random_graph(size, 0.1)
    # create a dataframe with the edges
    edges = pd.DataFrame(columns=['source', 'target', 'weight'])
    for i in range(size):
        for j in range(size):
            if random_G[i][j] == 1:
                edges = pd.concat([edges, pd.DataFrame({'source': [i+1], 'target': [j+1], 'weight': [1]})])

    edges.to_csv(f'code/randoms/{size}.txt', index=False, header=False, sep='\t')



In [ ]:
for size in sizes:
    rec_random = pd.read_csv(f'results/{size}/M', sep='\t', header=None).to_numpy()
    random = pd.read_csv(f'randoms/{size}.txt', sep='\t', header=None)
    adj_matrix = np.zeros((size, size))
    for row in random.iterrows():
        adj_matrix[row[1][0]-1][row[1][1]-1] = 1
        adj_matrix[row[1][1]-1][row[1][0]-1] = 1

    frob = np.linalg.norm(adj_matrix - rec_random, ord="fro")
    print(f"|| M*({size}) - M({size}) || = {frob**2}")

|| R*(100) - R(100) || = 30.999999999999996
|| R*(200) - R(200) || = 6303.0
|| R*(300) - R(300) || = 14480.0
|| R*(400) - R(400) || = 27052.0
|| R*(500) - R(500) || = 41006.0
|| R*(600) - R(600) || = 579.0
|| R*(700) - R(700) || = 82908.0
|| R*(800) - R(800) || = 112228.00000000001
|| R*(900) - R(900) || = 138134.0
|| R*(1000) - R(1000) || = 173905.00000000003


In [ ]:
print(np.linalg.eigvals(rec_polblogs_np))
print(np.linalg.eigvals(polblogs))


[ 7.40820189e+01+0.00000000e+00j  5.99408643e+01+0.00000000e+00j
 -2.93661038e+01+0.00000000e+00j ... -1.78895202e-32+8.31561623e-33j
 -1.78895202e-32-8.31561623e-33j  2.46119623e-33+0.00000000e+00j]
[ 7.4082016e+01+0.j  5.9940865e+01+0.j -2.9366104e+01+0.j ...
  3.1631281e-32+0.j -7.9873754e-33+0.j  2.8597886e-35+0.j]


In [ ]:
# compute the rank of the adjacency matrix of the polblogs graph
import numpy as np
print(np.linalg.matrix_rank(polblogs))

NameError: name 'polblogs' is not defined